In [1]:
import numpy as np
import pandas as pd


In [4]:
df = pd.DataFrame({'text':['people watch campus' , ' campus watch campus' , 'people write comment' , 'campus write comment'], 'output':[1,1,0,0]})

In [3]:
df


text  outpu
0   people watch campus      1
1   campus watch campus      1
2  people write comment      0
3  campus write comment      0

In [5]:
from sklearn.feature_extraction.text import CountVectorizer

In [6]:
cv = CountVectorizer()


In [7]:
bow =cv.fit_transform(df['text'])

In [9]:
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campus': 0, 'write': 4, 'comment': 1}


In [12]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 1 1 0]]
[[2 0 0 1 0]]


In [13]:
cv.transform(['campus watch and write comment of campus']).toarray()

array([[2, 1, 0, 1, 1]])

In [13]:
n-grams


In [14]:
from

SyntaxError: invalid syntax (ipython-input-1763543092.py, line 1)

In [15]:
cv=  CountVectorizer(ngram_range=(2,2))

In [16]:
bow = cv.fit_transform(df['text'])

In [18]:
cv.vocabulary_


{'people watch': 2,
 'watch campus': 4,
 'campus watch': 0,
 'people write': 3,
 'write comment': 5,
 'campus write': 1}

In [19]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())
print(bow[3].toarray())

[[0 0 1 0 1 0]]
[[1 0 0 0 1 0]]
[[0 0 0 1 0 1]]
[[0 1 0 0 0 1]]
