<a href="https://colab.research.google.com/github/suneetpaul/Natural-Language-Processing/blob/main/IMDB_reviews_bow_tfidf_NB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import nltk

In [ ]:
temp_df = pd.read_csv('/content/drive/MyDrive/IMDB Dataset.xls')

In [ ]:
df = temp_df.iloc[:10000]

In [ ]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
df.review[0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fa

In [ ]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(17)

In [ ]:
df =df.drop_duplicates()

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
import re

In [ ]:
def remove_tag(raw_text):
  cleaned_text = re.sub(re.compile('<.*?>'),'',raw_text)
  return cleaned_text

In [ ]:
df['review'] = df['review'].apply(remove_tag)

In [ ]:
df.review[0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.I would say the main appeal of the show is due to the fact that it goes where other shows wo

In [ ]:
df['review'] = df['review'].apply(lambda x:x.lower())

In [ ]:
df.review[0]

"one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me.the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs, sex or violence. its is hardcore, in the classic use of the word.it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.i would say the main appeal of the show is due to the fact that it goes where other shows wo

In [ ]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
sw_list = stopwords.words('english')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:

df['review'] = df['review'].apply(lambda x:[item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))

In [ ]:
x = df.iloc[: , 0:1]
y = df['sentiment']

In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [ ]:
y=  encoder.fit_transform(y)

In [ ]:
from sklearn.model_selection import train_test_split


In [ ]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2 , random_state=42)

In [ ]:
x_train.shape , y_train.shape , x_test.shape , y_test.shape

((7986, 1), (7986,), (1997, 1), (1997,))

In [ ]:
x_train

review
6940  back 1993 sega released dull, lackluster video...
1919  10 viewings 20 years think crazy gang's best e...
718   hard praise film much. cgi dragon well done, l...
8599  rented horrible movie. worst think ever seen. ...
7950  *** spoilers***one worst films seen since last...
...                                                 ...
5737  cowboys james stewart walter brennan take herd...
5194  movie look feel put together matter days-kind ...
5393  total crap.i kind excited see film version see...
860   production quite surprise me. absolutely love ...
7278  cartoon network seems desperate ratings. begin...

[7986 rows x 1 columns]

In [ ]:
h

NameError: name 'h' is not defined

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer()

In [ ]:
x_train1 = cv.fit_transform(x_train['review']).toarray()
x_test1 = cv.transform(x_test['review']).toarray()

In [ ]:
x_train1.shape , x_test1.shape

((7986, 48247), (1997, 48247))

In [ ]:
from sklearn.naive_bayes import MultinomialNB , GaussianNB , BernoulliNB
from sklearn.metrics import classification_report , confusion_matrix , accuracy_score

In [ ]:
def model(model):
  model.fit(x_train1, y_train)
  y_pred = model.predict(x_test1)
  print(classification_report(y_test , y_pred))
  print(confusion_matrix(y_test , y_pred))
  print(accuracy_score(y_test , y_pred))


In [ ]:
model(MultinomialNB())

              precision    recall  f1-score   support

           0       0.84      0.88      0.86       985
           1       0.88      0.84      0.86      1012

    accuracy                           0.86      1997
   macro avg       0.86      0.86      0.86      1997
weighted avg       0.86      0.86      0.86      1997

[[865 120]
 [164 848]]
0.85778668002003


In [ ]:
model(GaussianNB())

              precision    recall  f1-score   support

           0       0.61      0.70      0.65       985
           1       0.66      0.55      0.60      1012

    accuracy                           0.63      1997
   macro avg       0.63      0.63      0.63      1997
weighted avg       0.63      0.63      0.63      1997

[[694 291]
 [452 560]]
0.627941912869304


In [ ]:
model(BernoulliNB())

              precision    recall  f1-score   support

           0       0.86      0.88      0.87       985
           1       0.88      0.86      0.87      1012

    accuracy                           0.87      1997
   macro avg       0.87      0.87      0.87      1997
weighted avg       0.87      0.87      0.87      1997

[[870 115]
 [141 871]]
0.871807711567351


In [ ]:
from sklearn.ensemble import RandomForestClassifier


In [ ]:
model(RandomForestClassifier())

              precision    recall  f1-score   support

           0       0.85      0.84      0.85       985
           1       0.85      0.86      0.85      1012

    accuracy                           0.85      1997
   macro avg       0.85      0.85      0.85      1997
weighted avg       0.85      0.85      0.85      1997

[[828 157]
 [145 867]]
0.8487731597396094


In [ ]:
cv1 = CountVectorizer(max_features=3000)

In [ ]:
x_train_bow = cv1.fit_transform(x_train['review'])
x_test_bow = cv1.fit(x_test['review'])

In [ ]:
x_train_bow.shape

(7986, 3000)

In [ ]:
def model(model):
  model.fit(x_train_bow, y_train)
  y_pred = model.predict(x_test_bow)
  print(accuracy_score(y_test , y_pred))
  print(classification_report(y_test , y_pred))
  print(confusion_matrix(y_test , y_pred))


In [ ]:
cv2 = CountVectorizer(ngram_range=(1,2))


In [ ]:
x_train_bow = cv2.fit_transform(x_train['review']).toarray()
x_test_bow = cv2.transform(x_test['review']).toarray()

In [ ]:
model(RandomForestClassifier())

In [ ]:
cv3 = CountVectorizer(ngram_range=(1,2) , max_features=5000)


In [ ]:
x_train_bow = cv3.fit_transform(x_train['review']).toarray()
x_test_bow = cv3.transform(x_test['review']).toarray()

In [ ]:
model(RandomForestClassifier())

0.8332498748122183
              precision    recall  f1-score   support

           0       0.82      0.84      0.83       985
           1       0.84      0.83      0.83      1012

    accuracy                           0.83      1997
   macro avg       0.83      0.83      0.83      1997
weighted avg       0.83      0.83      0.83      1997

[[829 156]
 [177 835]]


tf-idf

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tf= TfidfVectorizer()

In [ ]:
x_train_tf = tf.fit_transform(x_train['review'])
x_test_tf = tf.transform(x_test['review'])

In [ ]:
x_train_tf.shape

(7986, 48247)

In [ ]:
model = RandomForestClassifier()
model.fit(x_train_tf, y_train)
y_pred = model.predict(x_test_tf)
print(classification_report(y_test , y_pred))
print(confusion_matrix(y_test , y_pred))
print(accuracy_score(y_test , y_pred))

              precision    recall  f1-score   support

           0       0.85      0.87      0.86       985
           1       0.87      0.85      0.86      1012

    accuracy                           0.86      1997
   macro avg       0.86      0.86      0.86      1997
weighted avg       0.86      0.86      0.86      1997

[[858 127]
 [152 860]]
0.8602904356534802
